name = "releasator-api-my"
main = "src/index.ts"
compatibility_date = "2023-09-22"

[triggers]
crons = ["* * * * *", "0 * * * *"] # two cronjobs for posting and for healthcheck, leave as is

# run `npm run db:create -w packages/releasator-api`
# set the database_id accordingly to the output
[[d1_databases]]
binding = "DB"
database_name = "RE-MY-DB"
database_id = "c0da4b5b-c1c4-405a-a0a5-cf3b999a540e"

# DON'T FORGET to initialize your db with `npm run db:schema -w packages/releasator-api`
# if you are planing to develop locally, use `npm run db:schema:local -w packages/releasator-api` instead.
# also chack out other "db:" scripts in package.json

[vars]
# if you are planing to deploy your worker manually, store all secret vars here, it's safe
# if you're using CI, like GitHub, remove `wrangler.toml` from gitignore and use secrets to pass them cia env vars
# https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions

# non-secret vars below
DB_HOURS_OFFSET = 0 # left with 0 if your db server have correct date and time configuration

# service config is a JSON object
#   "guiRoot" - url to a deployed relesator GUI, set it to any correct value like `https://my-releasator-gui.your-cf-profile.pages.dev`, it should be changed later after GUI deploy
#   "allowedDemoDomains" - array of strings with domain names, allowed to be in demom links
#   "knownContributors" - array of objects for mentioning contributors in Slack, each object keys:
#   -  "githubLogin": contributor's github username
#   -  "slackUID": Slack member ID (can be copied from profile)
#   "knownProducts" - array of objects for using product names instead of repo names in release notes (also used for healthcheck), each object keys:
#   -  "repoString": product repository name (owner/repo format, like "rgb2hsl/releasator")
#   "notificationServices" - array of services to post release notes, only Slack currently avaiable so left it as is
#   "notificationDelayMinutes" - when release notes is created, it'll be postponed before posting for this amount of minutes
SERVICE_CONFIG = '{"guiRoot":"https://releasator-gui-my.pages.dev","allowedDemoDomains":["p2p.org"],"knownContributors":[{"githubLogin":"stanbuy","slackUID":"UD5F53EE8"}, {"githubLogin":"StarGonchar","slackUID":"U04RM4APV9C"},{"githubLogin":"jefferywa","slackUID":"U03NBL4KP5E"},{"githubLogin":"0xAxPx","slackUID":"U05DMH29DD3"},{"githubLogin":"Defaktos","slackUID":"U05EL018VM3"},{"githubLogin":"mnacharov","slackUID":"U046TUK4KEX"},{"githubLogin":"Dostoynov","slackUID":"U04THF8R28Z"},{"githubLogin":"viguenstepanyan","slackUID":"U039X22F3E1"},{"githubLogin":"rgb2hsl","slackUID":"U038LB8T87N"},{"githubLogin":"AnnaBarotova","slackUID":"U04S82DP91P"},{"githubLogin":"exromany","slackUID":"U050YV8E95E"},{"githubLogin":"Volchunovich","slackUID":"U039ZND4ZPA"}],"knownProducts":[{"repoString":"p2p-org/p2pwebsite","name":"P2P Website"},{"repoString":"p2p-org/p2pwebsite-staking-page","name":"P2P ETH Staking dApp"},{"repoString":"p2p-org/p2pwebsite-eth2-staking-backend","name":"P2P ETH Staking Backend"}],"notificationServices":["slack"],"notificationDelayMinutes":30}'

