name = "releasator"
main = "src/index.ts"
compatibility_date = "2023-09-22"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["* * * * *"] # * * * * * = run every minute

[[d1_databases]]
binding = "DB"
database_name = "RE"
database_id = "8afbd76c-b2ef-4f31-86ab-d6eb82a33833"

[vars]
SERVICE_CONFIG = '{ "allowedDemoDomains" : [ "google.com" ], "knownContributors": [ { "githubLogin": "rgb2hsl", "slackUID": "U038LB8T87N" } ], "knownProducts": [], "notificationServices": [ "slack" ], "notificationDelayMinutes": 0 }'
DB_HOURS_OFFSET = 0
